name: C/C++ CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  actions: write

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          gcc \
          cppcheck \
          valgrind \
          lcov \
          ruby \
          gcovr
        
    - name: Generate test runners
      working-directory: Unity/examples/comissions
      run: |
        ruby ../../auto/generate_test_runner.rb test/test_comissao.c test/test_runners/test_comissao_runner.c
        
    - name: Build for Valgrind
      working-directory: Unity/examples/comissions
      run: |
        make clean
        make CC=gcc CFLAGS="-g -Wall -Wextra"
        
    - name: Run Valgrind checks
      working-directory: Unity/examples/comissions
      run: |
        valgrind \
          --leak-check=full \
          --show-leak-kinds=all \
          --track-origins=yes \
          --error-exitcode=1 \
          ./comission_tests
        
    - name: Build with coverage
      working-directory: Unity/examples/comissions
      run: |
        make clean
        make CC=gcc CFLAGS="-g -Wall -Wextra -fprofile-arcs -ftest-coverage"
        
    - name: Run tests with coverage
      working-directory: Unity/examples/comissions
      run: |
        ./comission_tests
        
    - name: Generate coverage reports
      working-directory: Unity/examples/comissions
      run: |
        mkdir -p test-results
        # Generate gcov report
        gcov src/comissao.c
        # Generate lcov report
        lcov --capture --directory . --output-file test-results/lcov.info
        lcov --remove test-results/lcov.info '/usr/*' --output-file test-results/lcov-filtered.info
        # Generate HTML report
        genhtml test-results/lcov-filtered.info --output-directory test-results/coverage-html
        # Generate gcovr report
        gcovr --xml-pretty --root . --output test-results/coverage.xml
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: test-results-${{ github.run_number }}
        path: |
          Unity/examples/comissions/test-results/
        retention-days: 7
        
    - name: Run static analysis
      working-directory: Unity/examples/comissions
      run: |
        cppcheck \
          --enable=all \
          --suppress=missingIncludeSystem \
          --suppress=constParameterPointer \
          --suppress=unusedFunction \
          --error-exitcode=1 \
          -I src/ \
          -I ../../src/ \
          src/ \
        || echo "Cppcheck completed (warnings treated as errors)"