name: C/C++ CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  actions: write  # Required for uploading artifacts

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          gcc \
          cppcheck \
          valgrind \
          lcov \
          ruby
        
    - name: Generate test runners
      working-directory: Unity/examples/comissions
      run: |
        ruby ../../auto/generate_test_runner.rb test/test_comissao.c test/test_runners/test_comissao_runner.c
        
    - name: Build project
      working-directory: Unity/examples/comissions
      run: |
        make clean
        make
        
    - name: Run static analysis
      working-directory: Unity/examples/comissions
      run: |
        cppcheck \
          --enable=all \
          --suppress=missingIncludeSystem \
          --error-exitcode=1 \
          --includes-file=includes.txt \
          src/
        
    - name: Run unit tests
      working-directory: Unity/examples/comissions
      run: |
        ./comission_tests
        
    - name: Run memory checks
      working-directory: Unity/examples/comissions
      run: |
        valgrind \
          --leak-check=full \
          --show-leak-kinds=all \
          --track-origins=yes \
          --error-exitcode=1 \
          ./comission_tests
        
    - name: Generate coverage
      working-directory: Unity/examples/comissions
      run: |
        gcov src/comissao.c
        lcov --capture --directory . --output-file coverage.info
        lcov --remove coverage.info '/usr/*' --output-file coverage.info
        mkdir -p test-results
        mv coverage.info test-results/
        
    - name: Upload test results
      uses: actions/upload-artifact@v3
      with:
        name: test-results-${{ github.run_number }}
        path: |
          Unity/examples/comissions/test-results/coverage.info
          Unity/examples/comissions/src/comissao.c.gcov
        retention-days: 7