name: C/C++ CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          gcc \
          cppcheck \
          valgrind \
          lcov
        
    - name: Build project
      run: |
        make clean
        make
        
    - name: Run static analysis (cppcheck)
      run: |
        cppcheck \
          --enable=all \
          --suppress=missingIncludeSystem \
          --error-exitcode=1 \
          --inline-suppr \
          --force \
          src/
        
    - name: Run unit tests
      run: |
        ./comission_tests
        
    - name: Run memory checks (Valgrind)
      run: |
        valgrind \
          --leak-check=full \
          --show-leak-kinds=all \
          --track-origins=yes \
          --error-exitcode=1 \
          ./comission_tests
        
    - name: Generate coverage report
      run: |
        lcov --capture --directory . --output-file coverage.info
        lcov --remove coverage.info '/usr/*' --output-file coverage.info
        genhtml coverage.info --output-directory coverage-report
        
    - name: Upload test artifacts
      uses: actions/upload-artifact@v3
      with:
        name: test-results-${{ github.run_number }}
        path: |
          coverage.info
          coverage-report/
        retention-days: 7