name: C/C++ CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up GCC 11 (LTS version)
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc-11 g++-11
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-11 100
        sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-11 100
        sudo update-alternatives --set gcc /usr/bin/gcc-11
        sudo update-alternatives --set g++ /usr/bin/g++-11
    
    - name: Install dependencies
      run: |
        sudo apt-get install -y \
          build-essential \
          cppcheck \
          valgrind \
          lcov \
          ruby \
          gcovr \
          python3-pip
        pip install gcovr==5.2
        
    - name: Generate test runners
      working-directory: Unity/examples/comissions
      run: |
        ruby ../../auto/generate_test_runner.rb test/test_comissao.c test/test_runners/test_comissao_runner.c
        
    - name: Build with coverage
      working-directory: Unity/examples/comissions
      run: |
        make clean
        make CC=gcc-11 CFLAGS="-g -Wall -Wextra -fprofile-arcs -ftest-coverage"
        
    - name: Run tests
      working-directory: Unity/examples/comissions
      run: |
        mkdir -p test-results
        ./comission_tests
        
    - name: Process coverage with lcov only
      working-directory: Unity/examples/comissions
      run: |
        # Generate lcov report
        lcov --capture --directory . --output-file test-results/lcov.info
        lcov --remove test-results/lcov.info '/usr/*' --output-file test-results/lcov-filtered.info
        genhtml test-results/lcov-filtered.info --output-directory test-results/coverage-html
        
    - name: Upload coverage reports
      uses: actions/upload-artifact@v4
      with:
        name: coverage-reports
        path: |
          Unity/examples/comissions/test-results/lcov.info
          Unity/examples/comissions/test-results/lcov-filtered.info
          Unity/examples/comissions/test-results/coverage-html/
        retention-days: 7
        
    - name: Run Valgrind checks
      working-directory: Unity/examples/comissions
      run: |
        make clean
        make CC=gcc-11 CFLAGS="-g -Wall -Wextra"
        valgrind \
          --leak-check=full \
          --show-leak-kinds=all \
          --track-origins=yes \
          --error-exitcode=1 \
          ./comission_tests
        
    - name: Run static analysis
      working-directory: Unity/examples/comissions
      run: |
        cppcheck \
          --enable=all \
          --suppress=missingIncludeSystem \
          --suppress=constParameterPointer \
          --suppress=unusedFunction \
          --error-exitcode=1 \
          -I src/ \
          -I ../../src/ \
          src/