name: C/C++ CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  actions: write

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          gcc \
          cppcheck \
          valgrind \
          lcov \
          ruby \
          gcovr
        
    - name: Generate test runners
      working-directory: Unity/examples/comissions
      run: |
        ruby ../../auto/generate_test_runner.rb test/test_comissao.c test/test_runners/test_comissao_runner.c
        
    - name: Build with coverage instrumentation
      working-directory: Unity/examples/comissions
      run: |
        make clean
        # Explicitly set coverage flags
        make CC=gcc CFLAGS="-g -Wall -Wextra -fprofile-arcs -ftest-coverage"
        
    - name: Run tests to generate coverage data
      working-directory: Unity/examples/comissions
      run: |
        # Ensure the test-results directory exists
        mkdir -p test-results
        # Run tests to generate .gcda files
        ./comission_tests
        
    - name: Generate coverage reports
      working-directory: Unity/examples/comissions
      run: |
        # Process coverage data
        gcov -o . src/comissao.c
        lcov --capture --directory . --output-file test-results/lcov.info
        lcov --remove test-results/lcov.info '/usr/*' --output-file test-results/lcov-filtered.info
        genhtml test-results/lcov-filtered.info --output-directory test-results/coverage-html
        gcovr --root . --xml --output=test-results/coverage.xml
        
    - name: Upload coverage artifacts
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report-${{ github.run_number }}
        path: |
          Unity/examples/comissions/test-results/
        retention-days: 7
        
    - name: Build for Valgrind
      working-directory: Unity/examples/comissions
      run: |
        make clean
        make CC=gcc CFLAGS="-g -Wall -Wextra"
        
    - name: Run Valgrind checks
      working-directory: Unity/examples/comissions
      run: |
        valgrind \
          --leak-check=full \
          --show-leak-kinds=all \
          --track-origins=yes \
          --error-exitcode=1 \
          ./comission_tests
        
    - name: Run static analysis
      working-directory: Unity/examples/comissions
      run: |
        cppcheck \
          --enable=all \
          --suppress=missingIncludeSystem \
          --suppress=constParameterPointer \
          --suppress=unusedFunction \
          --error-exitcode=1 \
          -I src/ \
          -I ../../src/ \
          src/